# Generated by Django 3.0.5 on 2021-11-03 21:56

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Колличество')),
                ('measurement_unit', models.CharField(choices=[('кг', 'киллограмм'), ('г', 'грамм'), ('л', 'литер'), ('мл', 'миллилитер'), ('ч.л.', 'чайная ложка'), ('ст.л', 'столовая ложка')], max_length=16, verbose_name='единица измерения')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название тега')),
                ('colour', colorfield.fields.ColorField(default='#FFFFFFFF', max_length=18)),
                ('TagSlug', models.SlugField(verbose_name='Slug')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Изображение блюда')),
                ('description', models.TextField(verbose_name='Описание')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('cooking_time', models.IntegerField(verbose_name='Время приготовления')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ingredients', models.ManyToManyField(related_name='recipes', to='recipes.Ingredient')),
                ('tag', models.ManyToManyField(blank=True, related_name='recipes', to='recipes.Tag', verbose_name='Тег')),
            ],
        ),
    ]
